[package]
name = "c-ptr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoffset = "0.6.5"
once_cell = { git = "https://github.com/saethlin/once_cell", branch = "provenance" }
